package de.justgeek.swimdroid;

import android.app.Activity;
import android.graphics.Color;
import android.os.Bundle;
import android.util.Log;
import android.widget.TextView;

import java.text.DateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import de.justgeek.common.models.PoolLength;
import de.justgeek.common.models.Session;
import de.justgeek.common.models.SessionHistory;
import de.justgeek.common.util.BroadcastCallback;
import de.justgeek.common.util.BroadcastHelper;
import lecho.lib.hellocharts.model.Axis;
import lecho.lib.hellocharts.model.Line;
import lecho.lib.hellocharts.model.LineChartData;
import lecho.lib.hellocharts.model.PointValue;
import lecho.lib.hellocharts.view.LineChartView;

public class MainActivity extends Activity implements BroadcastCallback {

    private static final String TAG = "swimdroid.phone.main";
    private BroadcastHelper broadcastHelper = new BroadcastHelper();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        broadcastHelper.create(this, this);
        setContentView(R.layout.activity_main);

        SessionHistory sessionHistory = SessionHistory.load();
        updateDisplay(sessionHistory);
    }

    @Override
    protected void onResume() {
        super.onResume();
    }

    @Override
    protected void onStart() {
        super.onStart();
        broadcastHelper.connect(this);
    }

    @Override
    protected void onStop() {
        broadcastHelper.disconnect(this);
        super.onStop();
    }

    @Override
    protected void onPause() {
        super.onPause();
    }

    @Override
    public void handleBroadcast(String type, String data) {
        log("Got new broadcast: " + type);
        switch (type) {
            case "history":
                SessionHistory sessionHistory = SessionHistory.fromString(data);
                updateDisplay(sessionHistory);
                sessionHistory.store();
                break;
        }
    }

    private void updateDisplay(SessionHistory sessionHistory) {
        Session session = sessionHistory.getLastSession();
        if (session != null) {
            setTextFieldValue(R.id.sessionDate, toDateString(session.getStart()));
            setTextFieldValue(R.id.sessionDuration, toTimeString(session.getStart()) + " - " + toTimeString(session.getEnd()));
            setTextFieldValue(R.id.sessionLengths, "Lengths: " + session.getLengthCount());
            setTextFieldValue(R.id.sessionDuration, String.format("Time: %.2f minutes", session.activeTime() / 60000.0f));
            setTextFieldValue(R.id.sessionDistance, String.format("Distance %dm: ", session.distance()));
            setTextFieldValue(R.id.fastestDuration, String.format("Fastest length: %.2fs", session.fastestLength() / 1000.0f));
            setTextFieldValue(R.id.slowestDuration, String.format("Slowest lengths: %.2fs", session.slowestLength() / 1000.0f));
            setTextFieldValue(R.id.averageSpeed, String.format("Average speed %.2f: ", session.averageSpeed()));
            setTextFieldValue(R.id.sessionStrokes, "Total strokes: " + session.strokes());
            updateSpeedChart(session);
        }
    }

    private void updateSpeedChart(Session session) {
        List<PointValue> values = new ArrayList<PointValue>();

        for(PoolLength length: session.getLengths()) {
            float speed = length.getSpeed(session.getPoolLength());
            values.add(new PointValue(length.getStartTime(), speed));
            values.add(new PointValue(length.getEndTime(), speed));
        }

        Line line = new Line(values).setColor(Color.parseColor("#FF8800")).setCubic(false).setHasPoints(false);
        List<Line> lines = new ArrayList<Line>();
        lines.add(line);

        LineChartData data = new LineChartData();
        data.setLines(lines);
        data.setAxisXBottom(new Axis().setAutoGenerated(false));

        LineChartView chart = (LineChartView) findViewById(R.id.speedGraph);
        chart.setInteractive(false);
        chart.setLineChartData(data);
    }

    private void setTextFieldValue(int id, String newValue) {
        TextView textField = (TextView) findViewById(id);
        textField.setText(newValue);
    }

    private String toDateString(long timestamp) {
        DateFormat formater = DateFormat.getDateInstance();
        return formater.format(new Date(timestamp));
    }

    private String toTimeString(long timestamp) {
        DateFormat formater = DateFormat.getTimeInstance();
        return formater.format(new Date(timestamp));
    }

    private void log(String data) {
        Log.d(TAG, data);
    }

}
